!IPAR E RPAR
Program main
    !DECLARAÇÃO DE VARIÁVEIS PARA A DASSL
    EXTERNAL RES, JAC
    INTEGER NEQ, INFO(15), IDID, LRW, LIW, IWORK(22), IPAR(1)
    DOUBLE PRECISION T, Y(2), YPRIME(2), TOUT, RTOL, ATOL, RWORK(62), RPAR(3)
    !DECLARAÇÃO DE VARIÁVEIS DO PROBLEMA
    DOUBLE PRECISION H, FO, ST, KV, FI
    DOUBLE PRECISION HPRIME,FOPRIME
    DOUBLE PRECISION DT, TEND
    !FORMULAÇÃO DO PROBLEMA
    
    !ATRIBUINDO VALORES ÀS CONSTANTES
    ST=1.D0        !ÁREA TRANSVERSAL DO TANQUE
    KV=1.D0        !CONSTANTE DA VÁLVULA
    
    !DEFININDO A CONDIÇÃO DE CONTORNO
    FI=1.D0        !VAZÃO DE ENTRADA
    
    !DEFININDO CONDIÇÕES INICIAIS
    H =0.D0        !ALTURA DE LÍQUIDO NO TANQUE
    HPRIME=FI/ST   !DERIVADA DE H EM RELAÇÃO AO TEMPO
    FO=0.D0        !VAZÃO DE SAÍDA
    FOPRIME=0.D0   !DERIVADA DE F0 EM RELAÇÃO AO TEMPO
    
    !INICIANDO OS PARÂMETROS DA DASSL
    T=0.D0         !TEMPO ATUAL (TEMPO INICIAL NESSE CASO)
    DT=1.D-1       !TAMANHO DO PASSO NO TEMPO
    TEND=20.D0        !DURAÇÃO DA SIMULAÇÃO DO ENCHIMENTO DE TANQUE
    Y(1)=H         !PASSAGEM DA CONDIÇAO INICIAL PARA UM VETOR LEGIVEL PELA DASSL
    Y(2)=FO        !PASSAGEM DA CONDIÇAO INICIAL PARA UM VETOR LEGIVEL PELA DASSL
    YPRIME(1)=HPRIME     !PASSAGEM DA CONDIÇAO INICIAL PARA UM VETOR LEGIVEL PELA DASSL   
    YPRIME(2)=FOPRIME    !PASSAGEM DA CONDIÇAO INICIAL PARA UM VETOR LEGIVEL PELA DASSL
    TOUT=T+DT      !TEMPO FINAL DDO PRIMEIRO PASSO DA INTEGRAÇÃO NO TEMPO
    INFO=0         !VETOR CONTENDO OPÇOES DA DASSL. DEFAULT=0
    RTOL=1.D-6     !TOLERÂNCIA RELATIVA
    ATOL=1.D-8     !TOLERÂNCIA ABSOLUTA
    NEQ=2          !NÚMERO DE EQUAÇÕES
    LIW=22         !O CÁLCULO DESSE VALOR É ENSINADO NO CÓDIGO DA DASSL
    LRW=62         !O CÁLCULO DESSE VALOR É ENSINADO NO CÓDIGO DA DASSL
    !PASSAGEM DE VARIÁVEIS PARA A SUBROTINA RES()
    RPAR(1)=ST
    RPAR(2)=KV
    RPAR(3)=FI
    !ABRINDO ARQUIVOS PARA GRAVAÇÃO DE DADOS
    !path.txt
    !OPEN(8,FILE=trim(path)//'SAIDA.TXT')
    OPEN(8,FILE='Example1src/SAIDA.TXT')
    WRITE(8,*) 'TEMPO   H     FO'
    WRITE(*,*) 'TEMPO   H     FO'
    WRITE(8,"(F6.3,F6.3,F6.3)") T,Y !ESCREVE NO ARQUIVO DE SAÍDA O TEMPO, A ALTURA E A VAZÃO DE SAÍDA
    WRITE(*,"(F6.3,F6.3,F6.3)") T,Y 
    
    !ROTINA DE CHAMADA DA DASSL PARA INTEGRAÇÃO DO SISTEMA DE DAEs, EM PASSOS DE TEMPO DT, ATÉ O TEMPO FINAL TEND
    DO WHILE (T < TEND)
    CALL DDASSL (RES, NEQ, T, Y, YPRIME, TOUT, INFO, RTOL, ATOL, IDID, RWORK, LRW, IWORK, LIW, RPAR, IPAR, JAC) !INTEGRA O O SISTEMA
    TOUT=T+DT
    WRITE(8,"(F6.3,F6.3,F6.3)") T,Y
    WRITE(*,"(F6.3,F6.3,F6.3)") T,Y 
    ENDDO
end program
